import {firebaseConfig} from './firebase-config.js';
import {vowels,vowelSounds as sounds,consonants,compounds,allLetters,letterGroups,words,sentences,lessons,makeQuestion} from './course-data.js';
import {readProgress,writeProgress,mergeProgress,cleanProgress} from './progress.js';
const stages=[
 ['01','Meet the vowels','உயிர் எழுத்துகள்','Weeks 1–3 · 12 letters','Learn four vowels at a time. Listen, spot the shape, trace on paper, and say it. Contrast short and long vowels: அ / ஆ, இ / ஈ, உ / ஊ, எ / ஏ, ஒ / ஓ.','letters'],
 ['02','Consonant friends','மெய் எழுத்துகள்','Weeks 4–6 · 18 letters','Learn the consonants with the pulli dot. Group வல்லினம்: க் ச் ட் த் ப் ற்; மெல்லினம்: ங் ஞ் ண் ந் ம் ன்; இடையினம்: ய் ர் ல் வ் ழ் ள். Practise ல் / ள் / ழ் and ந் / ண் / ன் with an adult.','consonants'],
 ['03','Letters come together','உயிர்மெய் எழுத்துகள்','Weeks 7–12 · 216 combinations','Combine each of 18 consonants with 12 vowels. Start with க் + அ = க and க் + ஆ = கா. Learn three consonant families each week and revisit older families. Introduce ஆய்த எழுத்து ஃ separately.','compounds'],
 ['04','My first words','சொற்கள்','Weeks 13–16 · Familiar words','Build and read அம்மா, அப்பா, மரம், மலர், பல், பழம், நீர் and வீடு. Connect each word to a real object. Listen, build, read aloud, and use the word in conversation.','words'],
 ['05','Little sentences','வாக்கியங்கள்','Weeks 17–20 · Simple sentences','Build நான் தமிழ் படிக்கிறேன். and இது ஒரு மலர். Learn naming words, action words, and sentence order through pictures and everyday conversation.','sentences'],
 ['06','Speak with confidence','பேசிப் பழகலாம்','Weeks 21–24 · Everyday speech','Practise greetings, introductions, requests, and short stories. Say வணக்கம், என் பெயர்… and நன்றி. Read aloud with an adult and revisit sounds that need support.','speech']
];
let storage;try{storage=window.localStorage}catch{storage=null}
let progress=readProgress(storage);
let activeLesson=null,quizPool=null,quizScope='vowels';
let group='vowels',view='home',quizMode='identify',question=0,correct=0,answered=false,answer='',options=[],buildIndex=0,parts=[],speechRecognition=null,cloudSave=null;
const app=document.querySelector('#app');
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(sync=true){const persisted=writeProgress(storage,progress);document.querySelector('#stars').textContent=`☆ ${progress.stars} stars`;if(!persisted)document.querySelector('#cloud-status')?.replaceChildren('Device storage is unavailable. Progress will last for this session.');if(sync)cloudSave?.(cleanProgress(progress)).catch(()=>{document.querySelector('#cloud-status')?.replaceChildren('Cloud save unavailable. Progress is saved on this device.');});}
function award(letter){if(!progress.learned.includes(letter)){progress.learned.push(letter);progress.stars+=1;save();}}
function speak(text){if(!('speechSynthesis'in window)){return 'Audio is unavailable in this browser. Ask an adult to read it aloud.'}const voices=speechSynthesis.getVoices();const voice=voices.find(x=>x.lang.toLowerCase().startsWith('ta'));if(!voice)return 'A Tamil voice is not installed. Add a Tamil voice in your device speech settings, or practise with an adult.';speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ta-IN';u.voice=voice;u.rate=.7;speechSynthesis.speak(u);return 'Listen carefully, then try saying it.'}
if('speechSynthesis'in window)speechSynthesis.getVoices();
function go(v){speechRecognition?.abort();if('speechSynthesis'in window)speechSynthesis.cancel();if(v==='quiz'&&view!=='quiz'){question=correct=0;answer=''}if((v==='words'||v==='sentences')&&view!==v){buildIndex=0;parts=[]}view=v;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render();window.scrollTo(0,0)}
function render(){save(false);if(view==='home'){app.innerHTML=`<section class="welcome"><div><div class="eyebrow">A little learning, every day</div><h1>Let’s grow your Tamil!</h1><p>Listen to a letter. Say it out loud. Discover a new word. Your Tamil adventure starts here.</p><button class="primary" data-lesson="vowels-1">Start learning letters</button></div><div class="banner"><span class="big" lang="ta">அ</span><div><span class="tag">YOUR FIRST STEP</span><h2>Say hello to அ</h2><p>The first Tamil vowel.<br>A short, open “a” sound.</p><button class="secondary" data-practice="அ">♪ Listen & say</button></div></div></section><div class="section-title"><h2>Your learning path</h2><span class="meta">10–15 minutes a day</span></div><div class="grid">${stages.map(s=>`<article class="card"><div class="meta">CHAPTER ${s[0]}</div><div class="symbol" lang="ta">${s[2]}</div><h3>${s[1]}</h3><p>${s[3]}</p><button class="secondary" data-stage="${s[5]}">Explore lesson</button></article>`).join('')}</div><section class="card" style="margin-top:30px"><h3>Small steps, big discoveries</h3><p>${progress.learned.filter(x=>allLetters.includes(x)).length} letters practised · ${progress.quizzes} quizzes completed. Listen together and celebrate effort. Progress is saved on this device.</p><p id="cloud-status" class="meta">${cloudSave?'Firebase connected':'Firebase is not configured yet.'}</p></section>`}
else if(view==='letters'){const list=group==='vowels'?vowels:group==='consonants'?consonants:group==='aytham'?['ஃ']:compounds;app.innerHTML=`<div class="eyebrow">Look · listen · say</div><h1>A garden of Tamil letters</h1><p>12 vowels + 18 consonants + 216 combinations + 1 āytham = 247 letters. Tap a letter to practise.</p><div class="filters">${[['vowels','Vowels · 12'],['consonants','Consonants · 18'],['compounds','Combinations · 216'],['aytham','Āytham · 1']].map(([k,t])=>`<button class="${group===k?'active':''}" data-group="${k}">${t}</button>`).join('')}</div><div class="letters">${list.map((l,i)=>`<button class="letter" data-practice="${l}" lang="ta">${l}<small>${progress.learned.includes(l)?'✓ Practised':group==='vowels'?sounds[i]:'Listen & say'}</small></button>`).join('')}</div>`}
else if(view==='course'){app.innerHTML=`<div class="eyebrow">A guide for grown-ups</div><h1>From first sounds to little stories</h1><p>A flexible 24-week course for a six-year-old. Move at your child’s pace; repeat a stage whenever needed.</p><div class="course">${stages.map(s=>`<article class="card"><div class="symbol">${s[0]}</div><div><span class="tag">${s[3]}</span><h3>${s[1]} · <span lang="ta">${s[2]}</span></h3><p>${s[4]}</p><button class="secondary" data-stage="${s[5]}">Open activity</button></div></article>`).join('')}</div><article class="card" style="margin-top:24px"><h3>Your daily rhythm</h3><p>2 minutes: revisit familiar sounds. 4 minutes: learn two new letters or words. 4 minutes: play a recognition or building game. 3 minutes: listen and speak with an adult. Finish with a favourite word.</p><h3>When to move on</h3><p>Aim for 8 out of 10 correct on two separate days, plus confident reading aloud with an adult. Recognition is only one part of learning: assess listening, reading and speech together.</p><h3>About Tamil</h3><p>Tamil is a Dravidian language written from left to right. Vowel length matters. The pulli (்) marks a consonant without its inherent vowel. Pronunciation can change with word context, and spoken Tamil differs from formal written Tamil. Introduce Grantha letters ஜ, ஷ, ஸ, ஹ, க்ஷ and ஸ்ரீ later for borrowed words and names.</p></article>`}
else if(view==='lesson')renderLesson();else if(view==='lessons')renderLessons();else if(view==='progress')renderProgress();else if(view==='quiz')renderQuiz();else if(view==='words'||view==='sentences')renderBuilder();else if(view==='speech'){app.innerHTML=`<div class="eyebrow">Listen · repeat · speak</div><h1>Let’s talk Tamil</h1><p>Practise with an adult. Tap a phrase to hear it and try the microphone.</p><div class="grid">${['வணக்கம்','நன்றி','என் பெயர்','நான் தமிழ் படிக்கிறேன்.'].map(t=>`<button class="card" data-practice="${t}"><h2 lang="ta">${t}</h2><p>Listen & speak</p></button>`).join('')}</div>`}}
const shuffled=a=>a.map(v=>({v,k:Math.random()})).sort((a,b)=>a.k-b.k).map(x=>x.v);
function renderLessons(chapter='vowels'){
 const list=lessons.filter(l=>l.group===chapter);
 app.innerHTML=`<div class="eyebrow">One small step at a time</div><h1>${esc(stages.find(s=>(s[5]==='letters'?'vowels':s[5])===chapter)?.[1]||'Lessons')}</h1><p>Learn a few sounds together. Listen, point, and say them before moving on.</p><div class="grid">${list.map(l=>`<article class="card"><span class="tag">${l.week}</span><h3>${l.title}</h3><p lang="ta">${l.items.slice(0,4).join(' · ')}${l.items.length>4?' …':''}</p><div class="meta">${progress.lessons.includes(l.id)?'✓ Completed with an adult':`${l.items.length} things to practise`}</div><button class="primary" data-lesson="${l.id}">Open lesson</button></article>`).join('')}</div>`;
}
function renderLesson(){
 if(!activeLesson){renderLessons();return}
 const l=activeLesson;
 const isLetters=Boolean(letterGroups[l.group]);
 app.innerHTML=`<div class="eyebrow">${l.week} · Learn together</div><h1>${l.title}</h1><p>${l.tip}</p><div class="lesson-steps"><span>1. Listen</span><span>2. Point & say</span><span>3. Play & review</span></div><div class="${isLetters?'letters':'grid'}">${l.items.map(t=>`<button class="letter ${isLetters?'':'phrase'}" data-practice="${esc(t)}" lang="ta">${esc(t)}<small>${progress.learned.includes(t)?'✓ Practised':'Listen & say'}</small></button>`).join('')}</div><section class="card lesson-review"><h2>Let’s practise</h2><p>Listen to each sound and say it with an adult. Trace letters on paper or in the air. Then play a little game.</p><div class="actions">${isLetters&&l.items.length>1?'<button class="primary" id="lesson-quiz">Play a lesson quiz</button>':''}${l.group==='words'||l.group==='sentences'?`<button class="primary" data-builder="${l.group}">Build ${l.group}</button>`:''}<button class="secondary" id="complete-lesson" ${progress.lessons.includes(l.id)?'disabled':''}>${progress.lessons.includes(l.id)?'✓ Lesson completed':'We finished this lesson together'}</button></div><p class="meta">An adult should check reading and speech before marking this lesson complete.</p></section>`;
}
function renderProgress(){
 const letterCount=progress.learned.filter(x=>allLetters.includes(x)).length;
 app.innerHTML=`<div class="eyebrow">Every little try counts</div><h1>Look how you’re growing!</h1><div class="grid"><article class="card"><div class="symbol">${letterCount} / 247</div><h3>Letters practised</h3><p>Listening and speaking, one letter at a time.</p></article><article class="card"><div class="symbol">${progress.lessons.length} / ${lessons.length}</div><h3>Lessons completed</h3><p>Reviewed together with an adult.</p></article><article class="card"><div class="symbol">${progress.quizzes}</div><h3>Quizzes played</h3><p>Keep trying and celebrate your effort.</p></article></div><section class="card lesson-review"><h2>Recent quiz practice</h2>${progress.results.length?`<div class="table-scroll"><table><thead><tr><th>Practice</th><th>Game</th><th>Score</th><th>Date</th></tr></thead><tbody>${progress.results.slice(-10).reverse().map(r=>`<tr><td>${esc(lessons.find(l=>l.id===r.group)?.title||r.group)}</td><td>${r.mode==='listen'?'Listening':'Recognition'}</td><td>${r.score} / 10</td><td>${esc(new Date(r.date).toLocaleDateString())}</td></tr>`).join('')}</tbody></table></div>`:'<p>Your first quiz is waiting! Start with the vowels and try a recognition game.</p>'}<button class="primary" data-view="quiz">Play a quiz</button></section><section class="card lesson-review"><h2>For grown-ups</h2><p>These numbers track practice, not confirmed pronunciation mastery. Look for confident recognition on separate days and check reading aloud together.</p><p id="cloud-status">${cloudSave?'Progress is synced to Firebase on this browser’s anonymous account.':'Progress is saved on this device. Firebase configuration is pending.'}</p></section>`;
}
document.addEventListener('change',e=>{if(e.target.id==='quiz-scope'){quizScope=e.target.value;quizPool=null;activeLesson=null;question=correct=0;answer='';renderQuiz();document.querySelector('#quiz-scope').value=quizScope}});
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();go('home')});
function newQuestion(){const pool=quizPool||(quizScope==='pairs'?['அ','ஆ','இ','ஈ','உ','ஊ','எ','ஏ','ஒ','ஓ']:letterGroups[quizScope])||vowels;({answer,options}=makeQuestion(pool));answered=false}
function renderQuiz(){if(question===10){app.innerHTML=`<section class="quiz"><div class="eyebrow">You did it!</div><h1>${correct} out of 10</h1><p>Every try helps your Tamil grow. Practise the tricky letters with an adult.</p><button class="primary" id="restart">Play again</button></section>`;return}if(!answer)newQuestion();app.innerHTML=`<div class="eyebrow">Play & practice</div><h1>Little letter detective</h1><label class="quiz-select">Choose your letters <select id="quiz-scope"><option value="vowels">Vowels</option><option value="consonants">Consonants</option><option value="compounds">Combinations</option><option value="pairs">Short & long vowels</option></select></label>${quizPool?'<p class="meta">Practising the letters from your lesson.</p>':''}<div class="filters"><button data-mode="identify" class="${quizMode==='identify'?'active':''}">Find the letter</button><button data-mode="listen" class="${quizMode==='listen'?'active':''}">Listen & choose</button></div><section class="quiz"><div class="meta">QUESTION ${question+1} OF 10 · ${quizPool?"Lesson practice":quizScope}</div><div class="progress"><span style="width:${question*10}%"></span></div><h2>${quizMode==='identify'?'Find the matching letter':'Which letter do you hear?'}</h2>${quizMode==='identify'?`<div class="target" lang="ta">${answer}</div>`:'<button class="primary" id="quiz-listen">♪ Hear the letter</button>'}<div class="choices" style="margin-top:24px">${options.map(l=>`<button data-answer="${l}" lang="ta">${l}</button>`).join('')}</div><div id="feedback" class="feedback" aria-live="polite"></div><button class="secondary" id="next" hidden>Next question</button></section>`;document.querySelector('#quiz-scope').value=quizScope}
function renderBuilder(){const items=view==='words'?words:sentences;const item=items[buildIndex%items.length];app.innerHTML=`<div class="eyebrow">Put the pieces together</div><h1>${view==='words'?'My first Tamil words':'Make a little sentence'}</h1><section class="quiz"><span class="tag">${item.meaning}</span><div class="target" style="font-size:42px" lang="ta">${item.text}</div><button class="secondary" data-practice="${item.text}">♪ Listen & say</button><p>Tap the pieces in the right order.</p><div class="built" lang="ta">${parts.map(esc).join(view==='words'?'':' ')||'…'}</div><div class="wordbank">${shuffled(item.parts.map((v,i)=>({v,i}))).map(({v,i})=>`<button data-piece="${i}" ${parts.length&&parts._used?.includes(i)?'disabled':''}>${v}</button>`).join('')}</div><div class="actions"><button class="secondary" id="clear-build">Try again</button><button class="primary" id="check-build">Check my answer</button><button class="secondary" id="next-build">Next activity</button></div><div id="feedback" class="feedback" aria-live="polite"></div></section>`}
function practice(t){document.querySelector('#practice-content').innerHTML=`<div class="eyebrow">Your turn to shine</div><div class="target" style="font-size:${t.length>6?'38':'90'}px" lang="ta">${esc(t)}</div><p>Listen first. Then say it clearly.</p><div class="actions"><button class="secondary" id="hear">♪ Listen</button><button class="primary" id="mic">🎙 Try speaking</button><button class="secondary" id="mark">I practised with an adult</button></div><div id="speech-feedback" class="feedback" aria-live="polite"></div><label class="notice consent"><input type="checkbox" id="mic-consent"> A grown-up agrees to use browser speech recognition.</label><p class="notice">Microphone practice checks recognized text, not an expert pronunciation score. Your browser may send audio to its speech service. Ask a grown-up before using it.</p>`;document.querySelector('#practice').showModal();document.querySelector('#hear').onclick=()=>document.querySelector('#speech-feedback').textContent=speak(t);document.querySelector('#mark').onclick=()=>{award(t);document.querySelector('#speech-feedback').textContent='Lovely practice! Keep listening and trying.'};document.querySelector('#mic').onclick=()=>recognize(t)}
function normalize(t){return t.normalize('NFC').replace(/[\s.,!?।]/g,'')}
function recognize(target){if(!document.querySelector('#mic-consent').checked){document.querySelector('#speech-feedback').textContent='Ask a grown-up to agree before using the microphone.';return}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;const f=document.querySelector('#speech-feedback');if(!SR){f.textContent='Microphone recognition is unavailable here. Try Chrome over HTTPS, or practise with an adult.';return}speechRecognition?.abort();const r=new SR();speechRecognition=r;r.lang='ta-IN';r.interimResults=false;r.maxAlternatives=5;r.onstart=()=>{f.textContent='Listening… say it now.';document.querySelector('#mic').disabled=true};r.onresult=e=>{const result=e.results[0];const match=Array.from(result).some(x=>normalize(x.transcript)===normalize(target));f.textContent=match?'The words matched! Ask an adult to check your sounds too.':`I heard “${result[0].transcript}”. Listen and try again. Single letters can be hard for speech recognition.`;if(match)award(target)};r.onerror=e=>f.textContent=e.error==='not-allowed'?'Microphone permission was denied. You can still listen and practise with an adult.':`Could not hear you (${e.error}). Please try again.`;r.onend=()=>{const b=document.querySelector('#mic');if(b)b.disabled=false;if(f.textContent.startsWith('Listening'))f.textContent='No speech heard. Try again when ready.'};try{r.start()}catch{f.textContent='Microphone could not start. Please try again.'}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){if(b.dataset.view==='quiz'){quizPool=null;activeLesson=null}go(b.dataset.view)}if(b.dataset.lesson){activeLesson=lessons.find(l=>l.id===b.dataset.lesson);go('lesson')}if(b.id==='lesson-quiz'){quizPool=activeLesson.items;go('quiz')}if(b.id==='complete-lesson'){if(!progress.lessons.includes(activeLesson.id)){progress.lessons.push(activeLesson.id);progress.stars+=3;save()}renderLesson()}if(b.dataset.builder){go(b.dataset.builder)}if(b.dataset.stage){const chapter=b.dataset.stage==='letters'?'vowels':b.dataset.stage;renderLessons(chapter);view='lessons'}if(b.dataset.group){group=b.dataset.group;render()}if(b.dataset.practice)practice(b.dataset.practice);if(b.dataset.mode){quizMode=b.dataset.mode;question=correct=0;answer='';render()}if(b.dataset.answer&&!answered){answered=true;const right=b.dataset.answer===answer;if(right){correct++;progress.stars++;save()}document.querySelector('#feedback').textContent=right?'Yes! You found it.':'Good try! The answer is '+answer+'.';document.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);document.querySelector('#next').hidden=false}if(b.id==='next'&&answered){question++;if(question===10){progress.quizzes++;progress.results.push({group:activeLesson?.id||quizScope,mode:quizMode,score:correct,date:new Date().toISOString()});progress.results=progress.results.slice(-50);save()}newQuestion();render()}if(b.id==='restart'){question=correct=0;answer='';render()}if(b.id==='quiz-listen')document.querySelector('#feedback').textContent=speak(answer);if(b.dataset.piece!==undefined&&!b.disabled&&!parts._used?.includes(Number(b.dataset.piece))){const item=(view==='words'?words:sentences)[buildIndex%(view==='words'?words:sentences).length];parts.push(item.parts[Number(b.dataset.piece)]);parts._used=[...(parts._used||[]),Number(b.dataset.piece)];renderBuilder()}if(b.id==='clear-build'){parts=[];renderBuilder()}if(b.id==='next-build'){buildIndex++;parts=[];renderBuilder()}if(b.id==='check-build'){const item=(view==='words'?words:sentences)[buildIndex%(view==='words'?words:sentences).length];const right=parts.join(view==='words'?'':' ')===item.text;document.querySelector('#feedback').textContent=right?'You built it! Now try saying it aloud.':'Keep trying! Look at the example and check the order.';if(right)award(item.text)}});
document.querySelector('#close').onclick=()=>document.querySelector('#practice').close();document.querySelector('#practice').addEventListener('close',()=>{speechRecognition?.abort();if('speechSynthesis'in window)speechSynthesis.cancel();if(view==='letters')render()});go('home');
async function connectFirebase(){if(!firebaseConfig.apiKey||firebaseConfig.apiKey==='YOUR_API_KEY'||firebaseConfig.appId==='YOUR_APP_ID')return;try{const [{initializeApp},{getAuth,signInAnonymously},{getFirestore,doc,getDoc,setDoc}]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js')]);const firebase=initializeApp(firebaseConfig);const {user}=await signInAnonymously(getAuth(firebase));const ref=doc(getFirestore(firebase),'learners',user.uid);const snapshot=await getDoc(ref);if(snapshot.exists())progress=mergeProgress(progress,snapshot.data());cloudSave=p=>setDoc(ref,cleanProgress(p));save();render()}catch{document.querySelector('#cloud-status')?.replaceChildren('Firebase unavailable. Your progress is saved on this device.')}}connectFirebase();
